# OpenCRVS Dependencies Helm values
#
# DEPLOY:
#   helm upgrade --install opencrvs-deps oci://ghcr.io/opencrvs/opencrvs-dependencies-chart \
#     --namespace opencrvs-deps-dev \
#     --create-namespace \
#     --atomic \
#     --timeout 10m \
#     -f dependencies/values.yaml

chart_dev_mode: false
hostname: szicrvs.techno-associates.live

global:
  cluster:
    domain: szicrvs.techno-associates.live
    tlsSecretName: opencrvs-custom-tls

storage_type: pvc
storageClass: local-path

monitoring:
  enabled: false

backup:
  enabled: false

restore:
  enabled: false
