# OpenCRVS Services Helm values
#
# DEPLOY:
#   helm upgrade --install opencrvs oci://ghcr.io/opencrvs/opencrvs-services \
#     --timeout 1h \
#     --namespace opencrvs-dev \
#     --create-namespace \
#     --atomic \
#     -f opencrvs-services/values.yaml

hostname: opencrvs.com

ingress:
  ssl_enabled: true
  tls_resolver: ""
  tls_secret_name: opencrvs-tls

image:
  tag: v1.9.9

countryconfig:
  image:
    name: ghcr.io/opencrvs/ocrvs-farajaland
    tag: v1.9.0

elasticsearch:
  host: elasticsearch.opencrvs-deps-dev.svc.cluster.local
  port: 9200
  auth_mode: disabled

influxdb:
  host: influxdb-0.influxdb.opencrvs-deps-dev.svc.cluster.local
  port: 8086
  db: ocrvs

minio:
  host: minio-0.minio.opencrvs-deps-dev.svc.cluster.local
  port: "3535"
  # external_hostname is required so MinIO generates presigned URLs accessible from the browser
  external_hostname: minio.opencrvs.com
  auth_mode: disabled

redis:
  host: redis-0.redis.opencrvs-deps-dev.svc.cluster.local
  auth_mode: disabled

mongodb:
  host: mongodb-0.mongodb.opencrvs-deps-dev.svc.cluster.local
  auth_mode: disabled

postgres:
  host: postgres-0.postgres.opencrvs-deps-dev.svc.cluster.local
  port: 5432
  auth_mode: disabled

env:
  NODE_ENV: production
  QA_ENV: false

resources:
  memoryRequest: "256Mi"
  cpuRequest: "100m"
  memoryLimit: "2Gi"
  cpuLimit: "2"

gateway:
  port: 7070
  env:
    CHECK_INVALID_TOKEN: "true"
    CONFIG_SMS_CODE_EXPIRY_SECONDS: "600"
    CONFIG_TOKEN_EXPIRY_SECONDS: "604800"
    MINIO_BUCKET: "ocrvs"
    COUNTRY: FAR
    DISABLE_RATE_LIMIT: "false"
    LANGUAGES: "en,fr"

notification:
  env:
    COUNTRY: FAR
  port: 2020

data_seed:
  enabled: true
  env:
    ACTIVATE_USERS: "true"
